# Generated by Django 2.1.15 on 2021-02-07 04:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_published', models.DateTimeField(verbose_name='date published')),
                ('article_image', models.ImageField(upload_to='images/')),
                ('article_content', tinymce.models.HTMLField()),
                ('article_slug', models.SlugField()),
            ],
        ),
    ]
