# Generated by Django 2.1.15 on 2021-02-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
